name: Feature Request
description: Suggest an idea for Medisync
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? How will it help you?
    validations:
      required: true
